---
- hosts: all
  become: yes
  tasks: 
  - name: updating pacakages
    apt:
      update_cache: yes
  - name: installing tomcat
    apt:
      name: tomcat8
      state: present
  - name: deploying war file into webapps folder
    get_url:
      url: https://s3-us-west-2.amazonaws.com/myartifcat-bucket/gameoflife.war
      dest: /var/lib/tomcat8/webapps/
  - name: restart tomcat
    service:
      name: tomcat8
      state: restarted